# Generated by Django 4.2.7 on 2023-11-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmorpg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=64)),
                ('text', models.TextField(max_length=255)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmorpg.notice')),
            ],
        ),
    ]
